version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: Test@123
      MYSQL_DATABASE: bankappdb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - bankapp-net

  ollama:
    image: ollama/ollama
    container_name: ollama-cont
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - bankapp-net

  mainapp:
    build: .
    container_name: bankapp
    ports:
      - "8080:8080"
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: Test@123
      MYSQL_HOST: mysql
      MYSQL_DATABASE: bankappdb
      MYSQL_PORT: 3306
      OLLAMA_URL: http://ollama:11434
    depends_on:
      - mysql
    networks:
      - bankapp-net

volumes:
  mysql-data:
  ollama-data:

networks:
  bankapp-net:
